export const REQUEST_LOGIN ="Request User Login"
export const RECEIVE_LOGIN ="Receive User Logins"
export const REQUEST_REGISTRATION ="Request User Registration"
export const RECEIVE_REGISTRATION ="Receive User Registration"
export const AUTHENTICATION_PASS = "Authendication Passed"
export const AUTHENTICATION_FAILED = "Authendication Failed"
export const AUTHENTICATION_ERROR = "Authendication Error"